#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI-master

on:
  # schedule:
    # - cron: 40 23 * * *
  # push:
    # branches: 
      # - master
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 1000000

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: add extra package
        run: |
          rm -rf ./package/lean/luci-theme-argon  
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git package/luci-theme-atmaterial
          git clone https://github.com/tty228/luci-app-serverchan.git package/luci-app-serverchan
          git clone https://github.com/peter-tank/openwrt-minisign.git package/minisign
          git clone https://github.com/peter-tank/luci-app-dnscrypt-proxy2.git package/luci-app-dnscrypt-proxy2
          git clone https://github.com/project-openwrt/luci-app-unblockneteasemusic.git package/lean/luci-app-unblockneteasemusic
          # mkdir ./package/Parted
          # git clone https://github.com/lisaac/luci-app-diskman.git package/luci-app-diskman
          # mv ./package/luci-app-diskman/Parted.Makefile ./package/Parted/Makefile
          git clone https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk.git package/MentoHUST
          git clone https://github.com/BoringCat/luci-app-mentohust.git package/luci-app-mentohust
          # rm -rf ./package/lean/luci-app-dockerman
          git clone https://github.com/lisaac/luci-app-dockerman.git package/lean/luci-app-dockerman
          # git clone https://github.com/openwrt-dev/po2lmo.git
          # cd po2lmo
          # make && sudo make install
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git package/lean/luci-app-adguardhome
          git clone https://github.com/pymumu/openwrt-smartdns.git package/smartdns
          # Clone luci-app-openclash 项目
          svn co https://github.com/vernesong/OpenClash/branches/master/luci-app-openclash package/luci-app-openclash
          # svn co https://github.com/project-openwrt/openwrt/trunk/package/ctcgfw/luci-app-openclash package/luci-app-openclash
          # git clone https://github.com/destan19/OpenAppFilter && mv -f OpenAppFilter/* package && rm -rf OpenAppFilter && rm -f package/README.md
          # svn co https://github.com/Lienol/openwrt-package/trunk/lienol/luci-app-fileassistant package/luci-app-fileassistant
          # svn co https://github.com/Lienol/openwrt-package/trunk/lienol/luci-app-filebrowser package/luci-app-filebrowser

      # - name: add extra config
        # run: |
          # cp ./extra_config/config_generate ./package/base-files/files/bin/config_generate

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config



          #
          # ========================固件定制部分========================
          # 
          

          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          EOF

          # Hardening build options:
          # cat >> .config <<EOF
          # CONFIG_SDK=y
          # CONFIG_MAKE_TOOLCHAIN=y
          # EOF

          # 固件大小:
          cat >> .config <<EOF
          CONFIG_TARGET_KERNEL_PARTSIZE=20
          CONFIG_TARGET_ROOTFS_PARTSIZE=700
          EOF

          # 固件压缩:
          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_QCOW2_IMAGES=y
          EOF
          

          # 编译UEFI固件:
          # cat >> .config <<EOF
          # CONFIG_EFI_IMAGES=y
          # EOF
          

          # IPv6支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y
          EOF

          # SSL库
          cat >> .config <<EOF
          CONFIG_PACKAGE_libustream-mbedtls=y
          # CONFIG_PACKAGE_libustream-openssl is not set
          EOF
          
          # 多文件系统支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-fs-squashfs=y
          CONFIG_PACKAGE_kmod-fs-cifs=y
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-squashfs=y
          CONFIG_PACKAGE_kmod-fs-cifs=y
          CONFIG_PACKAGE_kmod-nls-utf8=y
          CONFIG_PACKAGE_kmod-nls-base=y
          CONFIG_PACKAGE_kmod-nls-cp936=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-crypto-misc=y
          CONFIG_PACKAGE_kmod-fs-ext4=y
          CONFIG_PACKAGE_kmod-fs-vfat=y
          EOF


          
          # USB3.0支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-storage-extras=y
          CONFIG_PACKAGE_kmod-usb-storage-uas=y
          CONFIG_PACKAGE_kmod-usb-uhci=y
          CONFIG_PACKAGE_kmod-scsi-generic=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          EOF
          

          # 常用LuCI插件选择:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-attendedsysupgrade=y
          CONFIG_PACKAGE_luci-app-clamav=y
          CONFIG_PACKAGE_luci-app-commands=y
          CONFIG_PACKAGE_luci-app-cshark=y
          CONFIG_PACKAGE_luci-app-diag-core=y
          # CONFIG_PACKAGE_luci-app-dnscrypt-proxy is not set
          CONFIG_PACKAGE_luci-app-dnscrypt-proxy2=y
          # CONFIG_PACKAGE_luci-app-dnscrypt-proxy2_INCLUDE_minisign is not set
          CONFIG_PACKAGE_dnscrypt-proxy2=y
          CONFIG_PACKAGE_luci-app-dnsforwarder=y
          CONFIG_PACKAGE_luci-app-dnspod=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-amule=y
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-baidupcs-web=y
          CONFIG_PACKAGE_luci-app-docker is not set
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_luci-app-dockerman_INCLUDE_docker_ce=y
          CONFIG_PACKAGE_luci-app-dockerman_INCLUDE_ttyd=y
          CONFIG_PACKAGE_luci-app-e2guardian=y
          CONFIG_PACKAGE_luci-app-familycloud=y
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-fwknopd=y
          CONFIG_PACKAGE_luci-app-nfs=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          CONFIG_PACKAGE_luci-app-openvpn-server=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-kodexplorer=y
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_DNS2SOCKS=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-uhttpd=y
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          CONFIG_PACKAGE_luci-app-verysync=y
          CONFIG_PACKAGE_luci-app-vsftpd=y
          CONFIG_PACKAGE_luci-app-usb-printer=y
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-n2n_v2=y
          CONFIG_PACKAGE_luci-app-qos=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-zerotier=y
          CONFIG_PACKAGE_luci-app-nlbwmon=y
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-accesscontrol=y
          CONFIG_PACKAGE_luci-app-netdata=y
          CONFIG_PACKAGE_luci-app-samba4=y
          CONFIG_SAMBA4_SERVER_NETBIOS=y
          # CONFIG_PACKAGE_autosamba is not set
          # CONFIG_PACKAGE_luci-app-samba is not set
          CONFIG_PACKAGE_luci-app-ipsec-vpnd=y
          CONFIG_PACKAGE_luci-app-pptp-server=y
          CONFIG_PACKAGE_luci-app-xlnetacc=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-app-unblockneteasemusic=y
          # CONFIG_PACKAGE_luci-app-unblockneteasemusic-mini is not set
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          # CONFIG_PACKAGE_luci-app-unblockneteasemusic-go is not set
          # CONFIG_PACKAGE_UnblockNeteaseMusic is not set
          CONFIG_PACKAGE_luci-app-udpxy=y
          # CONFIG_PACKAGE_luci-app-cifsd is not set
          CONFIG_PACKAGE_luci-app-softethervpn=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-app-shairplay=y
          CONFIG_PACKAGE_luci-app-transmission=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-wireguard=y
          CONFIG_PACKAGE_luci-app-travelmate=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-statistics=y
          CONFIG_PACKAGE_luci-app-vpnbypass=y
          CONFIG_PACKAGE_luci-app-squid=y
          CONFIG_PACKAGE_luci-app-privoxy=y
          CONFIG_PACKAGE_luci-app-pagekitec=y
          CONFIG_PACKAGE_luci-app-pppoe-relay=y
          CONFIG_PACKAGE_luci-app-tinyproxy=y
          # CONFIG_PACKAGE_luci-app-radicale is not set
          CONFIG_PACKAGE_luci-app-radicale2=y
          CONFIG_PACKAGE_luci-app-mjpg-streamer=y
          CONFIG_PACKAGE_luci-app-minidlna=y
          CONFIG_PACKAGE_luci-app-lxc=y
          # CONFIG_PACKAGE_luci-app-unbound is not set
          # CONFIG_PACKAGE_samba36-server is not set
          CONFIG_PACKAGE_samba4-libs=y
          CONFIG_PACKAGE_libpam=y
          CONFIG_PACKAGE_samba4-server=y
          CONFIG_PACKAGE_luci-i18n-advanced-reboot-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ahcp-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-attendedsysupgrade-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-clamav-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-commands-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-cshark-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-diag-core-zh-cn=y
          # CONFIG_PACKAGE_luci-i18n-dnscrypt-proxy-zh-cn is not set
          CONFIG_PACKAGE_luci-i18n-dynapoint-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-fwknopd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-lxc-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-minidlna-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mjpg-streamer-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-nfs-zh_Hans=y
          CONFIG_PACKAGE_luci-i18n-nlbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-noddos-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ntpc-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-openvpn-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-polipo-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-privoxy-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-qos-zh-cn=y
          # CONFIG_PACKAGE_luci-i18n-radicale-zh-cn is not set
          CONFIG_PACKAGE_luci-i18n-radicale2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-rp-pppoe-server-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-shairplay-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-squid-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-statistics-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-tinyproxy-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-transmission-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-travelmate-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-udpxy-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-uhttpd-zh-cn=y
          # CONFIG_PACKAGE_luci-i18n-unbound-zh-cn is not set
          CONFIG_PACKAGE_luci-i18n-upnp-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vnstat-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vpnbypass-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-watchcat-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wifischedule-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wireguard-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-mentohust=y
          CONFIG_PACKAGE_mentohust=y
          CONFIG_PACKAGE_luci-app-frps=y
          CONFIG_PACKAGE_luci-app-nfs=y
          CONFIG_PACKAGE_luci-app-music-remote-center=y
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-rclone=y
          EOF

          # Derry Apps:
          # cat >> .config <<EOF          
          # CONFIG_PACKAGE_luci-app-oaf=y
          # CONFIG_PACKAGE_appfilter=y
          # CONFIG_PACKAGE_kmod-oaf=y
          # EOF

          # Language(Python):
          cat >> .config <<EOF
          CONFIG_PACKAGE_python-passlib=y
          CONFIG_PACKAGE_python-bcrypt=y
          EOF
                   
          # LuCI主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_luci-theme-atmaterial=y
          EOF


          # Storage
          cat >> .config <<EOF
          CONFIG_PACKAGE_open-vm-tools=y
          EOF

          # 常用软件包:
          cat >> .config <<EOF
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_screen=y
          CONFIG_PACKAGE_tree=y
          CONFIG_PACKAGE_vim-fuller=y
          CONFIG_PACKAGE_wget=y
          CONFIG_PACKAGE_nginx=y
          CONFIG_PACKAGE_php7=y
          CONFIG_PACKAGE_unrar=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_zip=y
          CONFIG_PHP7_LIBFREETYPE=y
          CONFIG_PACKAGE_php7-fpm=y
          CONFIG_PACKAGE_php7-mod-curl=y
          CONFIG_PACKAGE_php7-mod-gd=y
          CONFIG_PACKAGE_php7-mod-iconv=y
          CONFIG_PACKAGE_php7-mod-json=y
          CONFIG_PACKAGE_php7-mod-opcache=y
          CONFIG_PACKAGE_php7-mod-session=y
          CONFIG_PACKAGE_php7-mod-zip=y
          CONFIG_PACKAGE_php7-mod-mbstring=y
          CONFIG_PACKAGE_zoneinfo-asia=y
          EOF

          # disk工具:
          cat >> .config <<EOF
          CONFIG_PACKAGE_btrfs-progs=y
          CONFIG_PACKAGE_kmod-md-mod=y
          CONFIG_PACKAGE_kmod-md-linear=y
          CONFIG_PACKAGE_kmod-md-raid456=y
          CONFIG_PACKAGE_mdadm=y
          CONFIG_PACKAGE_parted=y
          CONFIG_PACKAGE_lsblk=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_e2fsprogs=y
          EOF

          # 网络工具:
          cat >> .config <<EOF
          CONFIG_PACKAGE_openssh-sftp-client=y
          CONFIG_PACKAGE_openssh-sftp-server=y
          EOF
          
          # 虚拟化:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-kvm-amd=y
          # CONFIG_PACKAGE_kmod-kvm-intel=y
          # CONFIG_PACKAGE_kmod-kvm-x86=y
          # CONFIG_PACKAGE_qemu-bridge-helper=y
          # CONFIG_PACKAGE_qemu-firmware-efi=y
          # CONFIG_PACKAGE_qemu-firmware-pxe=y
          # CONFIG_PACKAGE_qemu-firmware-seabios=y
          # CONFIG_PACKAGE_qemu-firmware-seavgabios=y
          # CONFIG_PACKAGE_qemu-ga=y
          # CONFIG_PACKAGE_qemu-img=y
          # CONFIG_PACKAGE_qemu-keymaps=y
          # CONFIG_PACKAGE_qemu-x86_64-softmmu=y
          # CONFIG_PACKAGE_virtio-console-helper=y
          # CONFIG_QEMU_UI_VNC=y
          # EOF

          # features for Docker
          cat >> .config <<EOF
          CONFIG_DOCKER_KERNEL_OPTIONS=y
          # CONFIG_DOCKER_SECCOMP is not set
          CONFIG_DOCKER_RES_SHAPE=y
          # CONFIG_DOCKER_NET_OVERLAY is not set
          CONFIG_DOCKER_NET_MACVLAN=y
          # CONFIG_DOCKER_NET_TFTP is not set
          # CONFIG_DOCKER_STO_EXT4 is not set
          CONFIG_DOCKER_STO_BTRFS=y
          EOF

          # 
          # ========================固件定制部分结束========================
          # 


          # sed -i 's/KERNEL_PATCHVER:=4.9/KERNEL_PATCHVER:=4.19/g' ./target/linux/x86/Makefile
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 V=s
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) V=s || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
